packages:
  - "apps/*"
  - "packages/*"

allowBuilds:
  '@google/genai': true
  '@ffmpeg-installer/linux-x64': true
  esbuild: true
  protobufjs: true
  puppeteer: true
  appium: true
  edgedriver: true
  geckodriver: true
  msw: true
